const MOCK_DATA = {
  CATEGORIES: [
    "Electonica, audio y video",
    "Ipod",
    "Reproductores",
    "iPod Touch",
    "32GB",
  ],
  ITEMS: [
    {
      id: "1",
      title: "Apple Ipod Touch 5g 16gb Negro Igual a Nuevo Completo Unico!",
      price: {
        currency: "ARS",
        amount: 1.982,
        decimals: 2,
      },
      picture: "http://http2.mlstatic.com/D_987543-MLA31352339877_072019-I.jpg",
      condition: "nuevo",
      free_shipping: true,
      sold_quantity: 32,
      description: "This is a product that.....",
      address: {
        state_id: "12321321",
        state_name: "Capital Federal",
        city_id: "123213",
        city_name: "San isidro",
      },
    },
    {
      id: "2",
      title: "Test2",
      price: {
        currency: "ARS",
        amount: 1.98,
        decimals: 3,
      },
      picture: "http://http2.mlstatic.com/D_987543-MLA31352339877_072019-I.jpg",
      condition: "nuevo",
      free_shipping: true,
      sold_quantity: 32,
      description: "This is a product that.....",
      address: {
        state_id: "12321321",
        state_name: "Capital Federal",
        city_id: "123213",
        city_name: "San isidro",
      },
    },
    {
      id: "3",
      title: "Test 3",
      price: {
        currency: "ARS",
        amount: 1.98,
        decimals: 5,
      },
      picture: "http://http2.mlstatic.com/D_987543-MLA31352339877_072019-I.jpg",
      condition: "nuevo",
      free_shipping: true,
      sold_quantity: 32,
      description: "This is a product that.....",
      address: {
        state_id: "12321321",
        state_name: "Capital Federal",
        city_id: "123213",
        city_name: "San isidro",
      },
    },
    {
      id: "4",
      title: "test 4 titlte text",
      price: {
        currency: "ARS",
        amount: 1.98,
        decimals: 1,
      },
      picture: "http://http2.mlstatic.com/D_987543-MLA31352339877_072019-I.jpg",
      condition: "nuevo",
      free_shipping: true,
      sold_quantity: 32,
      description: "This is a product that.....",
      address: {
        state_id: "12321321",
        state_name: "Capital Federal",
        city_id: "123213",
        city_name: "San isidro",
      },
    },
  ],
  SINGLE_ITEM: {
    id: "1",
    title: "Apple Ipod Touch 5g 16gb Negro Igual a Nuevo Completo Unico!",
    price: {
      currency: "ARS",
      amount: 1.98,
      decimals: 111,
    },
    picture: "http://http2.mlstatic.com/D_987543-MLA31352339877_072019-I.jpg",
    condition: "nuevo",
    free_shipping: true,
    sold_quantity: 32,
    description: "This is a product that.....",
  },
};

export default MOCK_DATA;
